2025-02-27 19:58:28,429 - [ERROR] - Internal Server Error: /post/127/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('post_id_.html'), <traceback object at 0x00000235E340EA00>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: post_id_.html
2025-02-27 19:58:28,435 - [ERROR] - "GET /post/127/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:08:32,900 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x000001E69B8B5F80>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:08:32,902 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:10:13,399 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x000001E69B925B40>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:10:13,399 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:11:51,453 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x0000025DC684F8C0>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:11:51,454 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:13:37,341 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x00000171DCB25440>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:13:37,343 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:15:25,010 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x000002030C41C980>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:15:25,012 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:16:21,217 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x0000023303AA55C0>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:16:21,219 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:17:11,163 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x0000028847197AC0>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:17:11,165 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:18:01,599 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x000001F861C79340>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:18:01,600 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
2025-02-27 20:18:28,549 - [ERROR] - Internal Server Error: /post/news/create/ - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\utils\log.py - (<class 'django.template.exceptions.TemplateDoesNotExist'>, TemplateDoesNotExist('Wcreate_post.html'), <traceback object at 0x000001E48186BE00>) 
Traceback (most recent call last):
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: Wcreate_post.html
2025-02-27 20:18:28,551 - [ERROR] - "GET /post/news/create/ HTTP/1.1" 500 145 - C:\Users\Andrey\Projects\task_Django_News_Portal_Module-28.-logging\venv\Lib\site-packages\django\core\servers\basehttp.py - None 
